[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "nano-u"
version = "0.1.0"
description = "Nano-U segmentation project - reorganized layout"
authors = ["Your Name <you@example.com>"]

[tool.black]
line-length = 88
